import { Testimonial } from '../types';

export const testimonials: Testimonial[] = [
  {
    id: 'testimonial-1',
    name: 'João Silva',
    role: 'Síndico',
    company: 'Condomínio Residencial',
    content: 'Excelente serviço! A equipe da Fachadas MC realizou a limpeza da fachada do nosso condomínio com muita competência e profissionalismo. O resultado superou nossas expectativas.',
    avatar: '/testimonials/avatar-1.jpg',
    rating: 5,
  },
  {
    id: 'testimonial-2',
    name: 'Maria Santos',
    role: 'Gerente Comercial',
    company: 'Shopping Center',
    content: 'Contratamos a Fachadas MC para a limpeza pós-obra do nosso shopping e ficamos impressionados com a qualidade do serviço. A equipe é muito organizada e eficiente.',
    avatar: '/testimonials/avatar-2.jpg',
    rating: 5,
  },
  {
    id: 'testimonial-3',
    name: 'Pedro Oliveira',
    role: 'Diretor',
    company: 'Empresa de Tecnologia',
    content: 'A limpeza dos vidros da nossa sede ficou impecável. A Fachadas MC demonstrou grande conhecimento técnico e atenção aos detalhes. Recomendo fortemente!',
    avatar: '/testimonials/avatar-3.jpg',
    rating: 5,
  },
  {
    id: 'testimonial-4',
    name: 'Ana Costa',
    role: 'Proprietária',
    company: 'Edifício Comercial',
    content: 'Já contratamos a Fachadas MC várias vezes e sempre ficamos satisfeitos. O atendimento é excelente e o serviço é realizado com muita qualidade.',
    avatar: '/testimonials/avatar-4.jpg',
    rating: 5,
  },
  {
    id: 'testimonial-5',
    name: 'Carlos Mendes',
    role: 'Síndico',
    company: 'Condomínio Empresarial',
    content: 'A limpeza da fachada do nosso prédio comercial ficou perfeita. A equipe é muito profissional e atenciosa. Certamente contrataremos novamente.',
    avatar: '/testimonials/avatar-5.jpg',
    rating: 5,
  },
  {
    id: 'testimonial-6',
    name: 'Lucia Ferreira',
    role: 'Gerente',
    company: 'Hotel',
    content: 'A Fachadas MC realizou a limpeza dos vidros do nosso hotel com muita eficiência. O serviço foi concluído dentro do prazo e com excelente qualidade.',
    avatar: '/testimonials/avatar-6.jpg',
    rating: 5,
  },
]; 